Implement initial Crypto.com support
bhftbootcamp/CryptoAPIs.jl pull request #26
Opened 2024-04-14 19:16 UTC by germanzelentsov

Pull request contains the implementation of initial Crypto.com support, including some modules such as Candle, Ticker, and GetInstruments specified in https://github.com/bhftbootcamp/CryptoAPIs.jl/issues/5

The following issue will be resolved with this PR:

closes https://github.com/bhftbootcamp/CryptoAPIs.jl/issues/5 Implement initial Crypto.com support

### Pull request checklist

- [x] Did you bump the project version?
- [x] Did you add a description to the Pull Request?
- [ ] Did you add new tests?
- [ ] Did you add reviewers?

2024-04-14 20:31 UTC, gryumov commented on examples/Crypto/Spot.jl
> +#https://exchange-docs.crypto.com/exchange/v1/rest-ws/index.html#introduction
```suggestion
# Crypto/Spot
# https://exchange-docs.crypto.com/exchange/v1/rest-ws/index.html#introduction
```

2024-04-14 20:31 UTC, gryumov commented on docs/src/pages/Crypto.md
> +CryptoAPIs.Crypto.Data
```suggestion
CryptoAPIs.Cryptocom.CryptoClient
CryptoAPIs.Cryptocom.CryptoAPIError
CryptoAPIs.Cryptocom.Data
```

2024-04-14 20:32 UTC, gryumov commented on src/Crypto/Spot/API/GetInstruments.jl
> +    symbol::Maybe{String}
```suggestion
    symbol::String
```

2024-04-14 20:33 UTC, gryumov commented on src/Crypto/Crypto.jl
> +
```suggestion

```

2024-04-14 20:33 UTC, gryumov commented on src/Crypto/Spot/API/Ticker.jl
> +    h::Maybe{String}
```suggestion
    h::Maybe{Float64}
```

2024-04-14 20:35 UTC, gryumov commented on src/CryptoAPIs.jl
> +include("Crypto/Crypto.jl")
```suggestion
include("Coinbase/Coinbase.jl")
include("Crypto/Crypto.jl")
include("Gateio/Gateio.jl")
include("Upbit/Upbit.jl")
```

2024-04-15 18:23 UTC, dmitrii-doronin commented on src/Cryptocom/Cryptocom.jl
> +end
Can the API return `null` in result field? If so, can you give an example?

2024-04-15 18:24 UTC, dmitrii-doronin commented on src/Cryptocom/Spot/API/Candle.jl
> +    timeframe::Maybe{String} = nothing
Why have you decided to skip enums here?

2024-04-15 18:25 UTC, dmitrii-doronin commented on src/Cryptocom/Errors.jl
> +# UNHANDLED
`UNDEF` or `UNHANDLED`?

2024-04-15 18:42 UTC, dmitrii-doronin requested changes

2024-04-15 18:42 UTC, dmitrii-doronin commented on src/Cryptocom/Spot/API/Candle.jl
> +  t::Maybe{Int64}
It's a unix timestamp. You can do direct conversion to NanoDate here.

2024-04-15 18:42 UTC, dmitrii-doronin commented on src/Cryptocom/Spot/API/Candle.jl
> +  t::Maybe{Int64}
It's very dangerous to do that. Is it really a plausible response?

2024-04-15 18:42 UTC, dmitrii-doronin commented on src/Cryptocom/Spot/API/Candle.jl
> +    end_ts::Maybe{Int64} = nothing
Should be NanoDate here

2024-04-15 18:42 UTC, dmitrii-doronin commented on src/Cryptocom/Spot/API/GetInstruments.jl
> +struct GetInstrumentsStruct <:CryptocomData
Formatting

2024-04-15 18:42 UTC, dmitrii-doronin commented on src/Cryptocom/Spot/API/Ticker.jl
> +end
Maybe simply `Ticker` would be better?

2024-04-15 18:42 UTC, dmitrii-doronin commented on src/Cryptocom/Spot/API/Candle.jl
> +struct CandleStruct <: CryptocomData
Maybe a better name?

2024-04-18 10:45 UTC, dmitrii-doronin approved these changes
Looks good to me!

2024-04-18 12:43 UTC, gryumov commented on src/Cryptocom/Utils.jl
> +
```suggestion
```

2024-04-18 12:43 UTC, gryumov commented on src/Cryptocom/Spot/API/Candle.jl
> +    x == d14  && return "14D"
```suggestion
    x == d14 && return "14D"
```

2024-04-18 12:44 UTC, gryumov approved these changes

2024-04-18 12:45 UTC, merged